Repository go-gitea/go-sdk, pull requests merged in 2018-10, with the labels that each got.

#122 Feature/archive repos
  gitea/repo.go
Labels: kind/feature, lgtm/done

#124 fix golint path.
  Makefile
Labels: kind/deployment, lgtm/done

#123 add myself to maintainers
  MAINTAINERS
Labels: lgtm/done

#121 Adjust keys API
  gitea/repo_key.go
  gitea/user_key.go
Labels: kind/enhancement, lgtm/done

#125 Add deploy key changes
  gitea/repo_key.go
Labels: lgtm/done

#126 fix: Add secret to all webhook's payload where it has been missing
  gitea/hook.go
Labels: lgtm/done
