Repository go-gitea/go-sdk, pull requests merged in 2018-12, with the labels that each got.

#133 make Release.Target a required parameter
  gitea/release.go
Labels: kind/bug, lgtm/done

#134 Add `organization` field to `Team` struct.
  gitea/org_team.go
Labels: kind/enhancement, lgtm/done

#135 add commit file status
  gitea/hook.go
Labels: lgtm/done
