Repository go-gitea/go-sdk, pull requests merged in 2018-08, with the labels that each got.

#114 Fix for missing field in EditUserOption
  gitea/admin_user.go
Labels: kind/enhancement, lgtm/done

#117 Prepare for prioritize issues & update .gitignore for goland users
  gitea/issue.go
Labels: kind/feature, lgtm/done

#118 Fix a format problem in admin_user.go
  gitea/admin_user.go
Labels: kind/lint, lgtm/done
