Repository go-gitea/go-sdk, pull requests merged in 2018-11, with the labels that each got.

#128 Add zeripath to maintainers
  MAINTAINERS
Labels: lgtm/done

#129 Support for git refs listing API
  gitea/repo_refs.go
Labels: kind/feature, lgtm/done

#94 Add repo trees
  gitea/repo_tree.go
Labels: kind/feature, lgtm/done

#130 added recursive support to git trees api
  gitea/repo_tree.go
Labels: kind/bug, kind/enhancement, lgtm/done

#131 Update SDK to include `head_commit` in `PushPayload`.
  gitea/hook.go
Labels: kind/enhancement, lgtm/done
