Repository go-gitea/go-sdk, pull requests merged in 2019-01, with the labels that each got.

#136 Replace @JonasFranzDEV with @jonasfranz
  MAINTAINERS
Labels: lgtm/done

#138 Add commit structs
  gitea/repo_commit.go
Labels: kind/feature, lgtm/done

#132 Client: handle 409 HTTP code
  gitea/gitea.go
Labels: kind/enhancement, lgtm/done

#140 Revert PR #133
  gitea/release.go
Labels: kind/bug, lgtm/done
