Repository go-gitea/go-sdk, pull requests merged in 2019-05, with the labels that each got.

#168 fixed GetSingleCommit url bug
  gitea/repo_commit.go
Labels: kind/bug, lgtm/done

#169 Switch back to sha1 as key
  gitea/user_app.go
Labels: lgtm/done

#170 Feature - #5960 - SDK for editing a repo
  gitea/repo.go
Labels: kind/enhancement, lgtm/done

#171 Refactor codes to remove structs and depend them on code.gitea.io/gitea/modules/structs
  Makefile
  gitea/admin_org.go
  gitea/admin_repo.go
  gitea/admin_user.go
  gitea/attachment.go
  gitea/client.go
  gitea/fork.go
  gitea/git_blob.go
  gitea/git_hook.go
  gitea/go.mod
  gitea/go.sum
  gitea/hook.go
  gitea/issue.go
  gitea/issue_comment.go
  gitea/issue_label.go
  gitea/issue_milestone.go
  gitea/issue_tracked_time.go
  gitea/lfs_lock.go
  gitea/miscellaneous.go
  gitea/org.go
  gitea/org_member.go
  gitea/org_team.go
  gitea/org_type.go
  gitea/pull.go
  gitea/release.go
  gitea/repo.go
  gitea/repo_branch.go
  gitea/repo_collaborator.go
  gitea/repo_commit.go
  gitea/repo_file.go
  gitea/repo_key.go
  gitea/repo_refs.go
  gitea/repo_tag.go
  gitea/repo_tree.go
  gitea/repo_watch.go
  gitea/status.go
  gitea/user.go
  gitea/user_app.go
  gitea/user_email.go
  gitea/user_gpgkey.go
  gitea/user_key.go
  gitea/utils.go
Labels: lgtm/done, refactor

#172 Fix typo in pull requests API
  gitea/pull.go
Labels: lgtm/done
