Repository go-gitea/go-sdk, pull requests merged in 2019-04, with the labels that each got.

#159 Add option for client with custom http client
  gitea/gitea.go
Labels: kind/enhancement, lgtm/done

#156 Add API for manipulating Git hooks
  gitea/git_hook.go
Labels: kind/feature, lgtm/done

#160 Struct changes to satisfy #3789
  gitea/user_app.go
Labels: lgtm/done

#165 Move organization visibility from gitea to SDK and add it on CreateOptions
  gitea/org.go
  gitea/org_type.go
Labels: kind/enhancement, lgtm/done
